import logging
from datetime import datetime, timezone
from decimal import Decimal
from typing import Dict, Any

from sqlalchemy.ext.asyncio import AsyncSession
from backend.database.models import GrievanceDraft, GrievanceStatus

logger = logging.getLogger("DossierGeneratorService")


class DossierGeneratorService:
    """
    Automated complaint dossier generator conforming to SEBI SCORES (SCORES 2.0)
    and SMART ODR / National Cybercrime Reporting Portal specifications.
    """

    async def generate_dossier(
        self,
        db: AsyncSession,
        incident_summary: str,
        amount: float,
        scammer_details: Dict[str, Any],
        user_session_id: str = "sess_guest",
        dispute_type: str = "Financial Scam / Fraudulent Advisory",
    ) -> Dict[str, Any]:
        """
        Generates structured Markdown dossier and determines filing portal and document requirements.
        """
        reg_number = scammer_details.get("reg_number")
        intermediary_name = scammer_details.get("intermediary_name") or scammer_details.get("channel_handle") or "Unidentified Entity"
        upi_id = scammer_details.get("upi_id") or "N/A"
        channel_handle = scammer_details.get("channel_handle") or "N/A"
        domain = scammer_details.get("domain") or scammer_details.get("domain_or_apk") or "N/A"

        # Determine target filing portal
        if reg_number:
            filing_portal = "SEBI_SCORES"
        else:
            filing_portal = "CYBERCRIME_PORTAL"

        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Build Markdown Dossier
        dossier_markdown = f"""# FORMAL COMPLAINT DOSSIER
**Generated by Sangyan Rakshak Scam Shield Engine**  
**Date:** {now_str}  
**Target Portal:** {filing_portal}  
**Session ID:** `{user_session_id}`  

---

### I. INCIDENT IDENTIFICATION & PARTICULARS
* **Dispute / Fraud Category:** {dispute_type}
* **Entity / Scammer Name:** {intermediary_name}
* **SEBI Registration Number (if claimed):** `{reg_number or 'UNREGISTERED / FAKE'}`
* **Telegram / Social Handle:** `{channel_handle}`
* **Associated UPI Handle / Bank Details:** `{upi_id}`
* **Associated Web Portal / APK Domain:** `{domain}`
* **Total Disputed Financial Amount:** ₹{amount:,.2f} INR

---

### II. COMPLAINT NARRATIVE & INCIDENT SUMMARY
> {incident_summary.strip()}

---

### III. EVIDENTIARY AUDIT TRAIL & FRAUD MARKERS
1. **Unfeasible Financial Promise:** Representation of guaranteed returns violating SEBI (Investment Advisers) Regulations, 2013.
2. **Channel & UPI Traces:** Digital payment requests solicited via unapproved communication channels.
3. **Regulatory Status:** {'Claimed registration verified against SEBI database.' if reg_number else 'Unregistered entity engaging in unauthorized portfolio management / financial advice.'}

---

### IV. REQUESTED RELIEF & PRAYER
1. Immediate investigation and freezing of beneficiary account associated with `{upi_id}`.
2. Direct refund of disputed amount ₹{amount:,.2f} INR to the complainant's source bank account.
3. Issuance of blocking orders against channel `{channel_handle}` and web domain `{domain}`.

---
*Generated electronically under Section 65B of Indian Evidence Act / IT Act 2000 format requirements.*
"""

        required_documents = [
            "Bank Statement highlighting payment transfer to UPI ID / Account",
            "Full Telegram / WhatsApp chat screenshots showing return promises",
            "Payment transaction reference numbers (UTR / RRN)",
            "Copy of Government Identity Proof (Aadhaar / PAN Card)",
            "Copy of SEBI Verification Audit Log from Sangyan Rakshak",
        ]

        # Save to database async
        draft = GrievanceDraft(
            user_session_id=user_session_id,
            dispute_type=dispute_type,
            intermediary_name=str(intermediary_name),
            amount_lost=Decimal(str(round(amount, 2))),
            incident_summary=incident_summary,
            generated_scores_dossier=dossier_markdown,
            status=GrievanceStatus.DRAFT,
        )
        db.add(draft)
        await db.commit()

        return {
            "dossier_markdown": dossier_markdown,
            "filing_portal": filing_portal,
            "required_documents": required_documents,
        }


dossier_service = DossierGeneratorService()
